[package]
name = "rust-store-api"
version = "0.1.0"
authors = ["Abey Onalaja <Abey.onalaja@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.8"
actix-web = "1.0.0-beta"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"